// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/sakata-server/internal/app/handler"
	"github.com/K-Kizuku/sakata-server/internal/app/repository"
	"github.com/K-Kizuku/sakata-server/internal/app/service"
	"github.com/K-Kizuku/sakata-server/pkg/ristretto"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	cache := ristretto.New()
	iMessageRepository := repository.NewMessageRepository(cache)
	iMessageService := service.NewMessageService(iMessageRepository)
	iMessageHandler := handler.NewMessageHandler(iMessageService)
	root := handler.New(iMessageHandler)
	return root
}
